const INGREDIENTS_LOADED = 'GRAPHQL/INGREDIENTS_LOADED';
const ADD_INGREDIENT = 'GRAPHQL/ADD_INGREDIENT';
const LOADING = 'LOADING';
const SEARCHING = 'SEARCHING';
const ADD_TOAST = 'ADD_TOAST';
const REMOVE_TOAST = 'REMOVE_TOAST';

export {
  LOADING,
  SEARCHING,
  REMOVE_TOAST,
  ADD_TOAST,
  INGREDIENTS_LOADED,
  ADD_INGREDIENT
};
